servoMotor:
  motors:
    leftDrive : 0
    rightDrive" : 1
  enable: True
  address: 0x40
server:
  port: 5005
  address: 127.0.0.1
sound:
  fileName: dog-barking.wav
head:
  motor: 0
  lights: 0
  port: 6969
  address: 127.0.0.1
