servoMotor:
  motors:
    leftDrive : 0
    rightDrive : 1
  enable: True
  address: 0x40
server:
  port: 5005
  address: 192.168.43.14
sound:
  fileName: dog-barking.wav
digitalIO: 
  pins:
    led0: 0
forward:
  head:
    motor: 0
    lights: 0
    port: 5005
    address: 192.168.43.41


# servoMotor:
#   motors:
#     mainDrive: 0
# lights:
#   pin: 18
